### ISSUE TITLE
Question about Authorization

### ISSUE THREAD

**Issue by Obsolete01** [zmartzone/lua-resty-openidc#148] opened 2018-03-26 15:34 UTC
Question about the authorization piece on this .. I have this up and running but it is right now allowing everyone in.

I see you can lock it down using the below however when i try and add multiple email addresses using IF THEN OR it then allows nobody in .. My question is, how are others handling the Authorization piece for this ?

                        if res.id_token.sub ~= "email_here" then
                                ngx.exit(ngx.HTTP_FORBIDDEN)
                        end

**Comment by bodewig** [comment] 2018-03-28 17:02
This looks like a Lua coding question.

Doesn't something like

```
if res.id_token.sub ~= "first_allowed_email" or res.id_token.sub ~= "second_allowed_email" then
  ngx.exit(ngx.HTTP_FORBIDDEN)
end
```

work? You probably want to put the allowed addresses into a table and check `sub` is contained in that table, something like

```
local allowed_adresses = {
  ["emails_one"} = true,
  ["emails_two"} = true,
  ["emails_three"} = true,
}
if not allowed_addresses[res.id_token.sub] then
  ngx.exit(ngx.HTTP_FORBIDDEN)
end
```

**Comment by Obsolete01** [comment] 2018-03-28 17:04
And how would I validate the client_id in the access token?

**Comment by zandbelt** [comment] 2018-03-28 17:11
The access token is opaque to an openid connect client as you have configured with lua-resty-openidc so you cannot assume it has a particular format or client id associated with it. Perhaps you meant the id_token?

**Comment by Obsolete01** [comment] 2018-03-28 17:13
So if I pass the correct scope that issues me my id token and access token... How would I then perform authorization based on the client_id or sub in the access token.

**Comment by bodewig** [comment] 2018-03-28 17:40
If you know the access token has a format you can parse and you know its structure then you can write Lua code as the code above. In the general case an access token may be just an opaque string without any recognizable internal structure, as @zandbelt already said.

**Comment by Obsolete01** [comment] 2018-03-28 17:52
But do I need to decode the access token to view it or how do i do it

**Comment by bodewig** [comment] 2018-03-28 17:56
if your access token is an opaque string, you cannot decode it at all (but may be able to invoke the OP's token introspection endpoint if it offers one). If it happens to be a JWT you could use `cjson.decode` - this really depends on your OP and its configuration.

**Comment by Obsolete01** [comment] 2018-03-28 18:05
Ok so yes I see my access token in the logs and it is in the JWT format...Do I put that cjson.decode after the call to authenticate piece.... local residents,  err = etc?

**Comment by bodewig** [comment] 2018-03-28 18:17
Before calling `authenticate` there is no access token, so yes, you need to deal with it after `authenticate` returns. The (unparsed) access token will be in `res.access_token` using the same `res` you used to access the id token.

If you know it is a JWT you can run the access token returned through `oidc.jwt_verify` which will verify a few things and return the parsed json (and error information)

```
local parsed_token, token_err = oidc.jwt_verify(res.access_token, opts)
```

**Comment by Obsolete01** [comment] 2018-03-28 19:33
Cant seem to get it to work .. Would it look like this ?

          local res, err = require("resty.openidc").authenticate(opts)

          if err then
            ngx.status = 500
            ngx.say(err)
            ngx.exit(ngx.HTTP_INTERNAL_SERVER_ERROR)
          end

		  local parsed_token, token_err = oidc.jwt_verify(res.access_token, opts)

          if res.access_token.sub ~= "xxxxxx" then
          ngx.exit(ngx.HTTP_FORBIDDEN)
          end

          ngx.req.set_header("X-USER", res.id_token.sub)
      }

**Comment by bodewig** [comment] 2018-03-29 13:08
Maybe I've been too terse, sorry. When I said `oidc` I meant the opeinidc module you've loaded. So it would be more along the lines of

```
local oidc = require("resty.openidc")
local res, err = oidc.authenticate(opts)
-- deal with err not being nil
local parsed_token, token_err = oidc.jwt_verify(res.access_token, opts)
-- deal with token_err not being nil
-- check whether access token contains the claims you need
```

hope this helps.

**Comment by Obsolete01** [comment] 2018-03-29 13:25
Hum .. I still cannot see the decoded JWT or perform validation of the sub in the access token .. 

Would it look like this 
*************************
      local res, err = require("resty.openidc").authenticate(opts)

      if err then
        ngx.status = 500
        ngx.say(err)
        ngx.exit(ngx.HTTP_INTERNAL_SERVER_ERROR)
      end

      local oidc = require("resty.openidc")
      local res, err = oidc.authenticate(opts)
      -- deal with err not being nil
      local parsed_token, token_err = oidc.jwt_verify(res.access_token, opts)
      -- deal with token_err not being nil
      -- check whether access token contains the claims you need

      if res.access_token.sub ~= "xxxxxx" then
      ngx.exit(ngx.HTTP_FORBIDDEN)
      end

      ngx.req.set_header("X-USER", res.id_token.sub)
  }

**Comment by bodewig** [comment] 2018-03-29 13:43
`res.access_token` still is the unparsed JWT string, `parsed_token` is a Lua table which is the result of parsing the string. `parsed_token.sub` may or may not be what you are looking for (whether the `sub` claim is part of the JWT again depends on the OP).

**Comment by Obsolete01** [comment] 2018-03-29 14:31
Yes i have sub and Client_id in the JWT.
So is there nothing that outlines a spec as to how Authorization can be done via the access token in terms of the claims in the jwt

**Comment by bodewig** [comment] 2018-03-29 16:42
lua-resty-openidc's job is to run the authorization code grant flow for you and maybe perform some basic validations on your JWT(s) like "has it been issue dby the expected issuer", "am I the intended audience", "is it valid right now", "has it been signed correctly".

But when it comes to the real authorization decisions they will be highly dependent on the application itself and need to be coded by you.

I'm not sure what kind of spec you are looking for. In your case you may be interested in email addresses. Others will want to look at the scopes provided by the token, or some other claims that may be present representing groups or whatnot.

**Comment by Obsolete01** [comment] 2018-03-29 16:48
but doesnt resty.jwt-validators have the capabilites to decode the JWT and look at the claims?

**Comment by bodewig** [comment] 2018-03-29 17:03
lua-resty-openidc uses jwt-validators under the covers and you can pass a table with validators of your own as parameter to `jwt_verify` (the optional args after `opts`).

If you try to use that for authorization then any failed authorization will lead to `token_err` being non-`nil` and it will be difficult for you to distinguish an invalid token (e.g. expired) from one that doesn't match your authorization requirements.

Of course you can invoke one of the verify function of lua-resty-jwt yourself on the parsed token as an additional step in order to separate the verification step from your authorization step.

**Comment by Obsolete01** [comment] 2018-03-29 17:24
Interesting, so would it look like this

local oidc = require("resty.openidc")
local res, err = oidc.authenticate(opts)
-- deal with err not being nil
local parsed_token, token_err = oidc.jwt_verify(res.access_token, opts, sub=email)
-- deal with token_err not being nil
-- check whether access token contains the claims you need

**Comment by usernamecopied12** [comment] 2018-03-30 13:13
I have been trying to get this to also work for a long time and no luck .. I do not think this is possible. Which makes no sense as Access Token should be in charge of deny / access

**Comment by bodewig** [comment] 2018-03-30 15:12
@usernamecopied12  I'm afraid I don't understand what you are trying to get to work and what is not working - and in particular what you expect lua-resty-openidc to do.

**Comment by usernamecopied12** [comment] 2018-03-30 15:25
end goal - i want to decode the access token and show it in my nginx logs ..

I believe this can be done via the openidc.lua file but still trying to figure out the syntax

This looks to encode it 
ngx.log(ngx.DEBUG, "request body for "..ep_name.." endpoint call: ", ngx.encode_args(body))

**Comment by bodewig** [comment] 2018-03-30 18:44
If you know the access token is a JWT, then `jwt_verify` will decode it an return a Lua table representation of the payload. Whether your access token is a JWT depends on your OP and potentially its configuration.

**Comment by usernamecopied12** [comment] 2018-03-30 18:47
Do you have code I can use? Like an example please

**Comment by bodewig** [comment] 2018-03-30 20:22
just a few comments earlier https://github.com/zmartzone/lua-resty-openidc/issues/148#issuecomment-377229604

**Comment by usernamecopied12** [comment] 2018-03-30 20:24
But I want to see the token decoded .. just like i have id_token in my logs i want to see the same for the access token

**Comment by bodewig** [comment] 2018-03-30 20:45
Sorry, I thought the pseudo code would have been enough

```
local oidc = require("resty.openidc")
local res, err = oidc.authenticate(opts)
if err then
  ngx.log(ngx.DEBUG, "authentication failed")
  ngx.exit(ngx.HTTP_FORBIDDEN)
end
local parsed_token, token_err = oidc.jwt_verify(res.access_token, opts)
if token_err then
  ngx.log(ngx.DEBUG, "access token is not a valid JWT")
  ngx.exit(ngx.HTTP_FORBIDDEN)
end
local cjson = require "cjson"
ngx.log(ngx.DEBUG, "access token: " .. cjson.encode(decoded_access_token))
```

**Comment by bodewig** [comment] 2018-03-30 20:48
Oh, if you really only want to see it logged then you can stop after `oidc.jwt_verify` as this will log the JWT's payload to debug anyway.

**Comment by usernamecopied12** [comment] 2018-03-30 20:53
Ok so slight progress .. Now I am seeing the below in my logs ... 

access token: null

**Comment by usernamecopied12** [comment] 2018-03-30 21:28
So you said that if i want to see it logged that i can stop after the oidc.jwt_verify piece .. but see it where ?

local oidc = require("resty.openidc")
local res, err = oidc.authenticate(opts)
if err then
  ngx.log(ngx.DEBUG, "authentication failed")
  ngx.exit(ngx.HTTP_FORBIDDEN)
end
local parsed_token, token_err = oidc.jwt_verify(res.access_token, opts)
if token_err then
  ngx.log(ngx.DEBUG, "access token is not a valid JWT")
  ngx.exit(ngx.HTTP_FORBIDDEN)
end
local cjson = require "cjson"
ngx.log(ngx.DEBUG, "access token: " .. cjson.encode(parsed_token))

By using the above it shows the access_token as null

but then if i change the last line to the below it shows the access token but in JWT format ?

ngx.log(ngx.DEBUG, "access token: " .. (parsed_token))

**Comment by usernamecopied12** [comment] 2018-03-30 22:16
Wait, so the payload data is the access tokens data? I though this was the id tokens data?

**Comment by bodewig** [comment] 2018-03-31 08:49
@usernamecopied12 you are getting two tokens from the token endpoint, what your OP returns as access token is completely up to the OP.

Are you saying `parsed_token` is a JWT String (i.e. something that starts with `ey` and contains two dots? This is strange, I don't see how `jwt_verify` would return that. If the string represents a valid JWT then it will get logged in https://github.com/zmartzone/lua-resty-openidc/blob/master/lib/resty/openidc.lua#L1286

**Comment by usernamecopied12** [comment] 2018-03-31 08:54
I am trying a few things now and each time it will not show the true access token to me ... it will keep showing it in JWT format in my log ... yes it starts with ey

I am even trying the below now and still it is not decoding the JWT (access token) .. I can see the id token so i know that decoding is possible ....

                        local oidc = require("resty.openidc")
                        local res, err = oidc.authenticate(opts)
                        local parsed_token, token_err = oidc.jwt_verify(res.access_token, opts)
                        local cjson = require "cjson"
                        local text = cjson.encode(res.access_token)
                        local value = cjson.decode(text)
                        ngx.log(ngx.DEBUG, "access token: " .. cjson.encode(res.access_token))
                        ngx.log(ngx.DEBUG, "access token: " .. cjson.encode(parsed_token))
                        ngx.log(ngx.DEBUG, "access token: " .. cjson.decode(text))

**Comment by bodewig** [comment] 2018-03-31 08:59
`res.access_token` is the unparsed access token. It may or may not be a JWT. Can you paste it into https://jwt.io/ and get it decoded properly?

Right now I don't see how `parsed_token` can end up being the same as `res.access_token` I must be overlooking something. I can easily see how it would be `nil`, but then `token_err` will not be `nil`. Can you please log `token_err`?

**Comment by usernamecopied12** [comment] 2018-03-31 09:04
yes if i paste it in to jwt.io it will get decoded and I can see the claims ... 

If i do the following 

 ngx.log(ngx.DEBUG, "access token: " .. token_err)

I then see this in the log
access token: JWT doesn't specify kid but the keystore contains multiple RSA keys

But I still get the JWT in the log by doing this

ngx.log(ngx.DEBUG, "access token: " .. cjson.encode(res.access_token))

**Comment by bodewig** [comment] 2018-03-31 09:13
What this says is lua-resty-openidc fails to verify the JWT (which `jwt_verify` does, hence its name :-).

Your access token is signed and lua-resty-openidc is not able to figure out which key has been used to sign it. Your OP seems to indicate the key when signing the id token (the `kid` claim says "this is the key I used") but not when signing the access token.

`jwt_verify` will not return a parsed access token if it has not been able to verify the token. This is its contract.

In your case you can try using lua-resty-jwt - see https://github.com/SkyLothar/lua-resty-jwt/ - to parse `res.access_token` instead (most likely `load_jwt`, you will need to figure out the exact syntax yourself). You'd do so instead of calling `jwt_verify` after calling `authenticate`.

**Comment by usernamecopied12** [comment] 2018-03-31 10:18
Hum, what's it using to verify the key, do I need to define that under the opts?

**Comment by bodewig** [comment] 2018-03-31 10:41
If you know the (public in case of asymmetric crypto) key used by your OP, you can specify it as `opts.secret`.

The general approach taken by lua-resty-openidc is to assume the OP supports OpenID Connect Discovery http://openid.net/specs/openid-connect-discovery-1_0.html . It uses the discovery endpoint to load the JWK keystore from the OP. If there is only one key inside of this key store, then lua-resty-openidc will assume, this is the one used to sign JWTs. If there is more than one, then the OP must specify the key's id as part of the JWT. It seems to do that for the id token (unless you are also getting error messages for that, of course) but not for the access token.

**Comment by usernamecopied12** [comment] 2018-03-31 12:07
and where do i specify opts.secret ? is it in the below?

local parsed_token, token_err = oidc.jwt_verify(res.access_token, opts)

**Comment by usernamecopied12** [comment] 2018-03-31 13:16
so it looks like the kid that is in my header does not seem to be in the JWKS .. Which is strange ..

**Comment by bodewig** [comment] 2018-03-31 13:35
Judging from the error message the header of your access token JWT doesn't provide any `kid` at all (it is an optional claim) while - unless you also get error messages for the id token - your OP does provide one for the id token. There isn't anything lua-resty-openidc can do about that.

`opts` is the second paramter you pass to `jwt_verify` which is a Lua table and `opt.secret` is the shorthand for the value stored under the key `secret` inside of this table. https://github.com/zmartzone/lua-resty-openidc#sample-configuration-for-oauth-20-jwt-token-validation contains an example for using `opts.secret` and specifying the certificate that belongs to the public key.

**Comment by usernamecopied12** [comment] 2018-03-31 13:39
When i first redirect to my OP for authentication i see an access token & refresh .... if i take the access token and use jwt.io to decode I can see the below headers .. 

{
  "alg": "RS256",
  "kid": "oidc2"
}

I have checked the cert i used for the token manager and can confirm it is valid .. Something is not adding up here.

Then after i authenticate i see my id token decoded and in my logs

**Comment by bodewig** [comment] 2018-03-31 13:48
and this also is true for `res.access_token` when you parse it through jwt.io?

I am aware your log may contain sensitive information. Do you think there is any way you can provide a (anoymized) full log of what is going on along with the code you are using? Right now I am second guessing a lot and I don't think this is going to get us anywhere.

Also I'd need to know which version of lua-resty-openidc you are using.

**Comment by usernamecopied12** [comment] 2018-03-31 14:18
I can but that will take some time as I will have to change alot to hide my info .. But i figured out what the issue is with the kid .. I had to change the name to match what was in my JWKS (for some reason the name in my JWKS was now what i set it so i changed it to match what was in my JKWS) .... 

So right now access token is getting validated but again we are back to issue number 1 .. Which is my access token not getting decoded and sent to my nginx logs ...

                        local oidc = require("resty.openidc")
                        local res, err = oidc.authenticate(opts)
                          ngx.log(ngx.DEBUG, "Validation Starting")
                        local parsed_token, token_err = oidc.jwt_verify(res.access_token, opts)
                        local cjson = require "cjson"
                        local text = cjson.encode(res.access_token)
                        local value = cjson.decode(text)
                        ngx.log(ngx.DEBUG, "access token: " .. cjson.encode(res.access_token))
                        ngx.log(ngx.DEBUG, "access token: " .. cjson.encode(parsed_token))
                        ngx.log(ngx.DEBUG, "access token: " .. cjson.decode(text))
                        ngx.log(ngx.DEBUG, "access token: " .. token_err)
                        ngx.log(ngx.DEBUG, "Validation Complete")


I don't get it .. surely cjson.decode would just do it ?

**Comment by bodewig** [comment] 2018-03-31 14:35
Is `token_err` nil?

`cjson.encode(res.access_token)` won't do much, `cjson.encode` creates a JSON formatted string from a Lua table, `res.access_token` is your JWT string, not a Lua table at all.

I would expect `cjson.encode(parsed_token)` to give you the result you are looking for, but only if `token_err` is `nil`.

**Comment by usernamecopied12** [comment] 2018-03-31 14:36
crap now it shows me this

access token: jwt signature verification failed: Verification failed

**Comment by bodewig** [comment] 2018-03-31 14:42
The second "Verification failed" is directly from lua-resty-jwt. So according to lua-resty-jwt the cryptographic signature on your access token is not valid.

**Comment by usernamecopied12** [comment] 2018-03-31 14:44
Do i need to add the cert in my config somewhere? In some keystore ?

**Comment by bodewig** [comment] 2018-03-31 14:52
Back to where we've been a few hours ago :-) `opts.secret`

But in your case lua-resty-openidc thinks it has the correct key via discovery and the JWK, it is just that verification using that key fails. If you know the key, then use `opts.secret`.

Also if you don't care for the validity, just don't use `jwt_verify` at all but use lua-resty-jwt directly.

**Comment by usernamecopied12** [comment] 2018-03-31 15:01
Just to get it doing what I want yes i dont care about the validity

So I need to use something like this ?

                        local jwt = require "resty.jwt"
                        local jwt_obj = jwt:load_jwt(res.access_token)
                        local cjson = require "cjson"
                        ngx.log(ngx.DEBUG, "access token: " .. cjson.encode(jwt_obj))

**Comment by bodewig** [comment] 2018-03-31 15:06
it should work, yes, doesn't it?

**Comment by bodewig** [comment] 2018-03-31 15:09
Please have a look at https://github.com/SkyLothar/lua-resty-jwt#load--verify `jwt:load_jwt` will return more than just the JWT's payload. It returns a table which under the key `payload` contains the token's payload, In the most simple case you want

```
ngx.log(ngx.DEBUG, "access token: " .. cjson.encode(jwt_obj.payload))
```

if you only want the payload.

**Comment by usernamecopied12** [comment] 2018-03-31 15:10
FINALLY :)

I do need to get the validation working proper though :)

**Comment by bodewig** [comment] 2018-03-31 15:10
There will be something wrong with your key set up, but I don't think this is really related to this library. Can we now close this issue?

**Comment by usernamecopied12** [comment] 2018-03-31 15:11
yes sir .. THANK YOU SO MUCH

**Comment by bodewig** [comment] 2018-03-31 15:12
you're welcome

**Closed by bodewig** 2018-03-31 15:12 UTC

**Comment by usernamecopied12** [comment] 2018-03-31 15:27
one more question .. If i want to get just the sub from that payload how would i just print that ..

example ???

ngx.log(ngx.DEBUG, "access_token.sub=", cjson.encode(jwt_obj.payload.sub))

**Comment by usernamecopied12** [comment] 2018-03-31 15:51
just one last question .... Any idea how i would not print the " out

Because right now the below is making it print like this including the "" - res.access_token.sub="email", ngx.time()=1522511265, slack=nil

ngx.log(ngx.DEBUG, "res.access_token.sub=", cjson.encode(jwt_obj.payload.sub), ", ngx.time()=", ngx.time(), ", slack=", slack)

**Comment by usernamecopied12** [comment] 2018-03-31 19:54
Strange, still I cannot grant or deny access based on the access token?

**Comment by usernamecopied12** [comment] 2018-03-31 22:47
So from looking at the openidc.lua file it looks like this handles how you deny / approve access ... 
Even though I am now seeing my access token when i try and deny access on that it is just ignored .. AS soon as i do the same referencing id_token it is straight away picked up .... 

Do I need to update the openidc.lua file to get this to work?

**Comment by usernamecopied12** [comment] 2018-03-31 23:06
So I have been looking over the code again .. and it says that after the below you have a table with an id token and access token right .. So why can you then not allow or deny from that like you can with the id_token?

          -- call authenticate for OpenID Connect user authentication
          local res, err = require("resty.openidc").authenticate(opts)

          if err then
            ngx.status = 500
            ngx.say(err)
            ngx.exit(ngx.HTTP_INTERNAL_SERVER_ERROR)
          end

          -- at this point res is a Lua table with 3 keys:
          --   id_token    : a Lua table with the claims from the id_token (required)
          --   access_token: the access token (optional)
          --   user        : a Lua table with the claims returned from the user info endpoint (optional)

**Comment by usernamecopied12** [comment] 2018-03-31 23:34
@bodewig so something just dawned on me.... What I need to do if this. 

Validate the sub of the access token and confirm that it is one of three email addresses, if it it not throw an error. 

If it is then slow them access to the app. 

What I was trying to do say get the access token in to the log, and then do an if statement but that is not going to work. 

Real sorry about this but, if I just wanted to load and verify the subject to be one of three known email addresses, how would I do this

**Comment by bodewig** [comment] 2018-04-01 09:44
First of all, let me clarify that authorization is out of scope for lua-resty-openidc. It provides you with some of the tools you need to write your authorization decisions, but authorization is very application specific and you will have to write you own code to do it. lua-resty-openidc offers `authenticate`, obtaining the access token from the current session, invoking the introspection endpoint for an access token and ways to verify and parse JWTs as a public API, that's it.

If you decide to write your authorization code as a layer on top of lua-resty-openidc then you will need to learn some basics of the Lua programming language - which is a very small language - or you won't get far. An alternative I've seen in projects is to use nginx as a reverse proxy in front of your "real" application and code the authorization logic inside of that (and pass on the access token as an extra HTTP header from nginx to your application, `Authorization: Bearer ACCESS_TOKEN` would be an obvious choice). This allows you to write your authorization code in a language you are more comfortable with.

Now to your concrete question. After

```
local jwt_obj = jwt:load_jwt(res.access_token)
```

you do have the JWT's payload as a Lua table in `jwt_obj.payload` and the `sub` claim of it will be string you can reach via `jwt_obj.payload.sub` or `jwt_obj['payload']['sub']` both are equivalent. "Throw an error" is 

```
ngx.exit(ngx.HTTP_UNAUTHORIZED)
```

and the rest is a simple Lua [`if` statement](https://www.lua.org/manual/5.1/manual.html#2.4.4). One example of it is in https://github.com/zmartzone/lua-resty-openidc/issues/148#issuecomment-376960765 where you certainly need to replace `res.id_token.sub` with `jwt_obj.payload.sub` and `FORBIDDEN` with `UNAUTHORIZED`.

**Comment by usernamecopied12** [comment] 2018-04-01 10:07
Works like a charm .. I was doing the if statement but I was doing it like this

local jwt = require "resty.jwt"
local jwt_obj = jwt:load_jwt(res.access_token)
local cjson = require "cjson"
ngx.log(ngx.DEBUG, "res.access_token.sub=", jwt_obj.payload.sub, ", ngx.time()=", ngx.time(), ", slack=", slack)

local allowed_people = {
  ["email_one"] = true,
  ["emails_two"] = true,
  ["emails_three"] = true,
}
if not allowed_people [jwt_obj.payload.sub] then
  ngx.exit(ngx.HTTP_FORBIDDEN)
end

But when i change it to this it now works .. not sure why though? It is because this lua table it just stored in cache so the if statement would then need to be done right away ?

local jwt = require "resty.jwt"
local jwt_obj = jwt:load_jwt(res.access_token)

local allowed_people = {
  ["email_one"] = true,
  ["emails_two"] = true,
  ["emails_three"] = true,
}
if not allowed_people [jwt_obj.payload.sub] then
  ngx.exit(ngx.HTTP_FORBIDDEN)
end

**Comment by bodewig** [comment] 2018-04-01 10:15
I must admit I don't see the difference between the two code snippets apart from the missing debug statement which may cause an error if `slack` is undefined. Glad you've got a working solution now.

**Comment by usernamecopied12** [comment] 2018-04-01 10:17
ah wait, i know ... I wasn't using jwt_obj.payload.sub i was using res.access_token.sub ... 

This lua table, it is possible to view this table at all ?

**Comment by usernamecopied12** [comment] 2018-04-01 10:30
And in your own professional opinion, for authorization for an app what should be used, the access token claims or the id token claims?

**Comment by bodewig** [comment] 2018-04-02 07:08
First of all you need to understand the intended audience of the tokens. The id token is for the client, the access token is for the resource server. If you are only in one of the two roles than you are not supposed to care about the other token.

Sometimes resource server and client happen to be the same entity. Formally the id token is there to provide information about the authenticated user while the access token is supposed to provide the authorization information. In practice authorization decisions often need information about the user that is not available from the access token, so you start mixing things.

If you are the resource server and not the client and you need information about the user in order to decide about authorization then you shouldn't have access to the id token but would call the OP's UserInfo endpoint using the access token instead.
