### ISSUE TITLE
can not work with multi worker_processes

### ISSUE THREAD

**Issue by mars198** [zmartzone/lua-resty-openidc#342] opened 2020-07-13 06:56 UTC
i use worker_processes  30 in nginx.conf
when i visit a website, much 403 appear
```
#user  nobody;
worker_processes  30;

#error_log  logs/error.log;
#error_log  logs/error.log  notice;
#error_log  logs/error.log  info;

#pid        logs/nginx.pid;


events {
    worker_connections  1024;
}


http {
    include       mime.types;
    default_type  application/octet-stream;
    lua_package_path '/usr/local/IAM/lua/?.lua;;';
    lua_package_cpath '/usr/local/IAM/lua/?.so;;';
    lua_shared_dict discovery 50m;
    lua_shared_dict jwks 50m;
    lua_shared_dict introspection 50m;
    sendfile        on;
    keepalive_timeout  65;
server {
    listen       80;
    server_name  xxxxxxxxxx;
    resolver 114.114.114.114;
	access_by_lua '
        	local opts = {
        		redirect_uri_path = "/redirect_uri",
        		accept_none_alg = true,
			ssl_verify = "no",
        		discovery = "https://xxxxxxxxx/auth/realms/master/.well-known/openid-configuration",
        		client_id = "xxxxxxx",
        		client_secret = "xxxxxxxxxx",
        		redirect_uri_scheme = "http",
       			logout_path = "/logout",
       			redirect_after_logout_uri = "https://xxxxxxxxx/auth/realms/master/protocol/openid-connect/logout?redirect_uri=",
        		redirect_after_logout_with_id_token_hint = false,
        		session_contents = {id_token=true}
         	}
         	local res, err = require("resty.openidc").authenticate(opts)
         	if err then
           		ngx.status = 403
           		ngx.say(err)
           		ngx.exit(ngx.HTTP_FORBIDDEN)
         	end
      	';
    location / {
	proxy_pass   http://xxxxxxxxxx;
	proxy_http_version 1.1;
	proxy_set_header Host $host;
    }

}
```

<img width="1612" alt="Screen Shot 2020-07-13 at 14 42 51" src="https://user-images.githubusercontent.com/48704297/87279039-abc62d00-c518-11ea-8ef2-26d26e273789.png">
<img width="1612" alt="Screen Shot 2020-07-13 at 14 41 58" src="https://user-images.githubusercontent.com/48704297/87279036-a963d300-c518-11ea-89f7-65e8f9424e92.png">

**Comment by bodewig** [comment] 2020-07-24 16:19
duplicate of #341

**Closed by bodewig** 2020-07-24 16:19 UTC
